## Lecture 1

### Numpy

- one of the core packages for numerical computing in Python
- many packages are built on numpy
- numpy has been optimized for processing: faster due to memory access

In [1]:
#import Numpy with standard abbreviation
import numpy as np

### Variables 
We can think about variables as a name we assign to a particular object in python. For Example:


In [4]:
#assign a small array to a variable "a"
a = np.array([[1,1,2],[3,5,8]])

When we run the cell, we store the variable and it's value. We can see the variable's value by either typing the variable and pressing enter or using the print() function

In [5]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [6]:
print(a)


[[1 1 2]
 [3 5 8]]


#### Naming Variables
In this class, we are going to use snake case for naming variables.

#### Variables and objects
**object**: often encountered in Python documentation and tutorials

DEF: a bundle of properties and actions about something specific
EX:
- object: data frame
- properties: number of rows, number of columns, data created
- actions: selecting a row, adding a column

A variable is a name we give a specific object, and the same object can be referenced by different variables.
EX:
- The Sun = object
- sol = spanish word for Sun = variable

In practice: we will use object and variable interchangeably


### Types
Each object in Python has a type.

DEF: Type = what kind of object it is

We can also call the type of the object, the class of the object
We can see the type/class of an object by using the type function

In [7]:
type(a)


numpy.ndarray

The numpy.ndarray is the core object/data type in the NumPy package. We can check the type of an entry in the array by indexing:
    

In [8]:
print(a[0,0])

1


In [9]:
type(a[0,0])

numpy.int64

## How would you access the value 5 in the array?

In [10]:
print(a[1,1])

5


## Functions
'print' was our example of a python function

Functions take in a set of arguments, separated by commas, and use those arguments to create some output. There are several built-in funcions in Python, most of them are for interacting with the basic Python data types
- We can interchangeably say arguments or parameters. You will see argument more often in the documentation.


In [11]:
#We can ask for information about a function by executing ? followed by the function name:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


- first line is always the function showing all of its arguments in parenthesis. 
- Then a short description of what the function does. 
- finally a list of the arguments and a brief explanation about each of them.

You can see there are different types of arguments inside the parenthesis. Roughly speaking, a function has two types of arguments:
- **non-optional arguments**: arguments you need to specify for the function to do something
- **optional arguments**: arguemnts that are prefilled but can be over written if we specify them. Optional arguments appear inside the parenthesis

In [13]:
print('changing the default argument of a print function', end=' :)')

changing the default argument of a print function :)

## Attributes and Methods